<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/register" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->user['name']?>" name="name" class="form-control" placeholder="Nome" required>
              </div>
              
              <div class="form-group">
                <input type="email" value="<?= $this->view->user['email']?>"  name="email" class="form-control" placeholder="E-mail" required>
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->user['password']?>"  name="password" class="form-control" placeholder="Senha" required>
              </div>
              
              <? if(isset($this->view->error['registerError'])) { $error = unserialize($this->view->error['registerError']); ?> 
              
              <? foreach ($error as $key => $erro) { ?>
                
                <? if($erro == 'invalidName') { ?>
                  <div class="alert alert-danger" role="alert">
                    O nome necessita de 3 ou mais caracteres. Tente novamente.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                <? } ?>

                <? if($erro == 'usedEmail') { ?>
                  <div class="alert alert-danger" role="alert">
                    O endereço de e-mail já foi utilizado. Tente novamente.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                <? } ?>

                <? if($erro == 'invalidMail') { ?>
                  <div class="alert alert-danger" role="alert">
                    Endereço de e-mail inválido. Tente novamente.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                <? } ?>

                <? if($erro == 'invalidMail') { ?>
                  <div class="alert alert-danger" role="alert">
                    Endereço de e-mail inválido. Tente novamente.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                <? } ?>

                <? if($erro == 'shortPassword') { ?>
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    A senha necessita de 8 ou mais caracteres. Tente novamente.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                <? } ?>
                
              <? } ?> 
            <? } ?>

              


              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>