<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/exit">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->userinfo['name']?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->tweetsCount['total_tweets']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->following['total_following']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->followers['total_followers']?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="get" action="/connect_people">
								<div class="input-group mb-3">
									<input type="text" name="searchBy" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<? foreach ($this->view->searchResult as $key => $user) { ?>

				<div class="row mb-2">
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6">
										<?= $user['name']?>
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
										<? if($user['following_yn'] == 0) { ?>
											<a href="/action?action=follow&user_id=<?= $user['id']?>&searchBy=<?=$_GET['searchBy']?>" class="btn btn-sm btn-success">Seguir</a>
										<? } ?>

										<? if($user['following_yn'] == 1) { ?>	
											<a href="/action?action=unfollow&user_id=<?= $user['id']?>&searchBy=<?=$_GET['searchBy']?>" class="btn btn-sm btn-danger">Deixar de seguir</a>
										<? } ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			<? } ?>

		</div>
	</div>
</div>