<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/exit">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->userinfo['name']?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->tweetsCount['total_tweets']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->following['total_following']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->followers['total_followers']?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3" maxlength="280" required></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<? foreach ($this->view->tweets as $id_tweet => $tweet) { ?>

				<div class="row tweet">
					<div class="col">
						<p><strong><?= $tweet['name']?></strong> <small><span class="text text-muted">- <?= $tweet['date']?></span></small></p>
						<p><?= $tweet['tweet']?></p>
						<br />

					<? if($tweet['id_user'] == $_SESSION['id']) { ?>
						<form method="post", action="/deleteTweet" >
							<div class="col d-flex justify-content-end">
								<button type="submit" name="tweet_id" value="<?=$tweet['id']?>" class="btn btn-danger"><small>Remover</small></button>
							</div>
						</form>
					<? } ?>

					</div>
				</div>

			<? } ?>

			<div class="row mt-5 justify-content-center">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item">
							<a class="page-link" href="?pagina=1" tabindex="-1" aria-disabled="true">Primeira</a>
						</li>

						<?php for($i=1; $i <= $this->view->total_pages; $i++) { ?>

							<li class="page-item <?= $this->view->active_page == $i ? 'active' : '' ?>"><a class="page-link" href="?pagina=<?= $i ?>"><?= $i ?></i></a></li>

						<? } ?>
						
						<li class="page-item">
							<a class="page-link" href="?pagina=<?=$this->view->total_pages ?>">Última</a>
						</li>
					</ul>
				</nav>
			</div>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/connect_people" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
<div>